### PR TITLE
Adds Luqas support

### PR DESCRIPTION
**Pull request by mathiasbl**
Adds support for Luqas.
Luqas adds several gauges to your controller.

Qbus config with all the different gauges
[qbusconfig.json](https://github.com/user-attachments/files/15578305/qbusconfig.json)

See results
image
image

### CODE REVIEW

**Comment by thomasddn** [comment]
Great work!

Since I don't have a Luqas module, are entity names like `LQS El. Totaal` hard coded by Qbus or can you alter them with Qbus Serial Manager software?

**Comment by mathiasbl** [comment]
> Great work!
> 
> Since I don't have a Luqas module, are entity names like `LQS El. Totaal` hard coded by Qbus or can you alter them with Qbus Serial Manager software?

I'm not sure. Not confident to try it out.
Like I commented in the code, we could assume the unit kWh as 'total' state class.
The rest is either A, kW or W which are measurements.

**Comment by mathiasbl** [comment]
> Great work!
> 
> Since I don't have a Luqas module, are entity names like `LQS El. Totaal` hard coded by Qbus or can you alter them with Qbus Serial Manager software?

I'm not sure. Not really confident to try it out.
Like I commented in the code, we could assume kWh is a 'total' state class.

**Comment by LennartMart** [comment]
I think it's semi-fixed. See https://files.qbus.be/assets/documentatie/Handleidingen/Qbus%20SystemManagerIII_Handleiding_Update%2012-2023.pdf#page=214 

afbeelding

"Maak uitgangen aan" creates all necessary outputs, but you can choose the prefix (default EMM for the old module, LQS for LuQas)

**Comment by thomasddn** [comment]
@mathiasbl Can you change the implementation so it sets `state_class` based on the unit?

**Comment by mathiasbl** [comment]
I'm a bit in a dilemma on how to handle it properly. People could have their own gauges of these variants. It's not always safe to assume kWh is always a total. It could be a monthly, daily, .. aggregate.

**Comment by thomasddn** [comment]
Sorry @mathiasbl, but shouldn't it be total_increasing in most (or even all) cases? See https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

And doesn't this answer your previous comment?

**Comment by mathiasbl** [comment]
I disagree.

Most are live measurement except for the 'Dag', 'Nacht' and 'Totaal' values. 
Those values represent the total consumption since they installed the digital meter as a result this matches the 'total' state.

**Comment by thomasddn** [comment]
Yeah, you are right, I was confused. I'll merge and release later this week!

**Comment by thomasddn** [comment]
Version v0.7.0 released :rocket:

**Comment by Wisent39** [comment]
Kan het zijn dat sinds de officiele Qbus integratie, de Luqas info niet meer beschikbaar is?

**Pull request merged**
